<?php
/**
 * @file
 *
 * The plugin definition for the 'Transition US Homepage' Panels layout
 */
$plugin = array(
  'title' => t('Transition US Homepage'),
  'icon' => 'hometus.png',
  'theme' => 'hometus',
  'css' => 'hometus.css',
  'panels' => array(
      'banner_top' => t('Top banner'),
      'top_left' => t('Top main left'),
      'top_right' => t('Top side right'),
      'banner_above' => t('Above banner'),
      'above_quad_1' => t('Above quad 1'),
      'above_quad_2' => t('Above quad 2'),
      'above_quad_3' => t('Above quad 3'),
      'above_quad_4' => t('Above quad 4'),
      'middle_left' => t('Middle main left'),
      'middle_right' => t('Middle side right'),
      'banner_below' => t('Below banner'),
      'below_quad_1' => t('Below quad 1'),
      'below_quad_2' => t('Below quad 2'),
      'below_quad_3' => t('Below quad 3'),
      'below_quad_4' => t('Below quad 4'),
      'bottom_left' => t('Bottom main left'),
      'bottom_right' => t('Bottom side right'),
      'banner_bottom' => t('Bottom banner'),
    ),
);
